replicaCount: 1

image:
  repository: sofiencloud/fiq
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "fiq"
fullnameOverride: "fiq"

service:
  type: ClusterIP
  port: 3000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

sidekiq:
  enabled: false
  replicaCount: 1
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 250m
    #   memory: 256Mi

env:
  RAILS_ENV: production
  RACK_ENV: production
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "true"
  SECRET_KEY_BASE: "your-secret-key-base"
  FIQ_FULL_DATABASE_USERNAME: "your-database-username"
  FIQ_FULL_DATABASE_PASSWORD: "your-database-password"
  DB_HOST: "fiq.godwinogbara.com"

