replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "fiq"
fullnameOverride: "fiq"

service:
  type: ClusterIP
  port: 80

replicaCount: 1

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

sidekiq:
  enabled: true
  replicaCount: 1
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 250m
    #   memory: 256Mi
