apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.nameOverride }}-ingress"
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: fiq.godwinogbara.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nameOverride }}
                port:
                  number: {{ .Values.service.port }}